services:
  todo-app:
    container_name: todo-ngrx-container
    build: .
    ports:
      - '1234:4200'
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - todo-ngrx-network

networks:
  todo-ngrx-network:
    name: todo-ngrx-network
    driver: bridge
